sudo: false
language: python
python:
  - 3.6
  - 3.7
notifications:
  email: false
install:
  - pip install -r test-requirements.txt
stages:
  - test

stage: test

script:
  - pytest --cov=hello tests

after_success:
  - codecov

after_failure:
  - codecov