language: python
cache: pip

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          python: 3.6

moban:
  image: python:3.5
  before_script:
    - pip install moban
    - git clone https://github.com/moremoban/pypi-mobans ../pypi-mobans

  script:
    - moban
    - git diff --exit-code

install:
    - pip install -r test-requirements.txt
    - pip setup.py install
