sudo: false
language: python
python:
  - 3.5
  - 3.6
notifications:
  email: false
install:
  - pip install -r test-requirements.txt
stages:
  - test

stage: test

script:
  - pytest tests

after_success:
  - codecov

after_failure:
  - codecov