language: python
cache: pip

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          python: 3.6

install:
    - pip install -r test-requirements.txt

moban:
  image: python:3.6
  before_script:
    - pip install moban
    - pytest

after_success:
  - codecov
